Tech_No_Logic/Models/Subrubric.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Tech_No_Logic.Models
{
    public class Subrubric
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(40, ErrorMessage = "Максимальна довжина {2}", MinimumLength = 2)]
        public string Name { get; set; }

        public int RubricId { get; set; }

        [ForeignKey("RubricId")]
        public virtual Rubric Rubric { get; set; }
    }
}

Tech_No_Logic/Controllers/SubrubricsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Barter.DAL;
using Tech_No_Logic.Models;

namespace Tech_No_Logic.Controllers
{
    [Authorize(Roles = "Moderator")]
    public class SubrubricsController : Controller
    {
        private UnitOfWork unitOfWork = null;

        public SubrubricsController()
        {
            unitOfWork = new UnitOfWork();
        }

        public SubrubricsController(UnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        // GET: Subrubrics
        public ViewResult Index()
        {
            return View(unitOfWork.Repository<Subrubric>().GetAll() as IEnumerable<Subrubric>);
        }

        // GET: Subrubrics/Details/5
        public ActionResult Details(int id = 0)
        {
            Subrubric subrubric = unitOfWork.Repository<Subrubric>().Get(c => c.Id == id);
            if (subrubric == null)
            {
                return HttpNotFound();
            }
            return View(subrubric);
        }

        // GET: Subrubrics/Create
        public ActionResult Create()
        {
            ViewBag.RubricId = new SelectList(unitOfWork.Repository<Rubric>().GetAll() as IEnumerable<Rubric>, "Id", "Name");
            return View();
        }

        // POST: Subrubrics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Subrubric subrubric)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Repository<Subrubric>().Add(subrubric);
                unitOfWork.SaveChanges();
                return RedirectToAction("Index", "Moderator");
            }
            return RedirectToAction("Index", "Moderator");
        }

        // GET: Subrubrics/Edit/5
        public ActionResult Edit(int id = 0)
        {
            Subrubric subrubric = unitOfWork.Repository<Subrubric>().Get(c => c.Id == id);
            if (subrubric == null)
            {
                return HttpNotFound();
            }

            ViewBag.RubricId = new SelectList(unitOfWork.Repository<Rubric>().GetAll() as IEnumerable<Rubric>, "Id", "Name", subrubric.RubricId);

            return View(subrubric);

        }

        // POST: Subrubrics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Subrubric subrubric)
        {
            if (subrubric.Name != string.Empty)
            {
                unitOfWork.Repository<Subrubric>().Attach(subrubric);
                unitOfWork.SaveChanges();

                return RedirectToAction("Index", "Moderator");
            }
            return RedirectToAction("Index", "Moderator");

        }

        // GET: Subrubrics/Delete/5
        public ActionResult Delete(int id = 0)
        {
            Subrubric subrubric = unitOfWork.Repository<Subrubric>().Get(c => c.Id == id);
            if (subrubric == null)
            {
                return HttpNotFound();
            }

            return View(subrubric);
        }

        // POST: Subrubrics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subrubric subrubric = unitOfWork.Repository<Subrubric>().Get(c => c.Id == id);
            unitOfWork.Repository<Subrubric>().Delete(subrubric);
            unitOfWork.SaveChanges();
            return RedirectToAction("Index", "Moderator");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tech_No_Logic/Views/Subrubrics/Create.cshtml
@model Tech_No_Logic.Models.Subrubric

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Subrubric</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RubricId, "Rubric", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RubricId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RubricId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Tech_No_Logic/Views/Subrubrics/Delete.cshtml
@model Tech_No_Logic.Models.Subrubric

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Subrubric</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rubric.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rubric.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tech_No_Logic/Views/Subrubrics/Details.cshtml
@model Tech_No_Logic.Models.Subrubric

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Subrubric</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Rubric
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rubric.Name)
        </dd>

        <dt>
            Subrubric
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Tech_No_Logic/Views/Subrubrics/Edit.cshtml
@model Tech_No_Logic.Models.Subrubric

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Subrubric</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RubricId, "Rubric", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RubricId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RubricId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Tech_No_Logic/Views/Subrubrics/Index.cshtml
@model IEnumerable<Tech_No_Logic.Models.Subrubric>

@{
    ViewBag.Title = "Index";
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Rubric
        </th>
        <th>
            Subrubric
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Rubric.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "Subrubrics", new { id = item.Id }, null) |
            @Html.ActionLink("Details", "Details", "Subrubrics", new { id = item.Id }, null) |
            @Html.ActionLink("Delete", "Delete", "Subrubrics", new { id = item.Id }, null)
        </td>
    </tr>
}

</table>