Tech_No_Logic/Models/UserSkillWanted.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Tech_No_Logic.Models
{
    public class UserSkillWanted
    {
        [Key]
        public int Id { get; set; }

        public int SubrubricId { get; set; }

        [ForeignKey("SubrubricId")]
        public virtual Subrubric Subrubric { get; set; }

        [Required]
        public string UserId { get; set; }

        [ForeignKey("UserId")]
        public virtual ApplicationUser ApplicationUser { get; set; }

        [Required]
        public string Name { get; set; }

        public string Description { get; set; }
    }
}

Tech_No_Logic/Controllers/UserSkillWantedsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Barter.DAL;
using Microsoft.AspNet.Identity;
using Tech_No_Logic.Models;

namespace Barter.Controllers
{
    [Authorize(Roles = "User,Moderator,Admin")]
    public class UserSkillWantedsController : Controller
    {
        private UnitOfWork unitOfWork = null;

        public UserSkillWantedsController()
        {
            unitOfWork = new UnitOfWork();
        }

        public UserSkillWantedsController(UnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        // GET: UserSkillWanted
        public ActionResult Index()
        {
            return View(unitOfWork.Repository<UserSkillWanted>().GetAll() as IEnumerable<UserSkillWanted>);
        }

        // GET: UserSkillWanted/Create
        public ActionResult Create()
        {
            ViewBag.UserId = Guid.Parse(User.Identity.GetUserId());
            ViewBag.SubrubricId = new SelectList(unitOfWork.Repository<Subrubric>().GetAll() as IEnumerable<Subrubric>, "Id", "Name");
            return View();
        }

        // POST: UserSkillWanteds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserSkillViewModel userSkill)
        {
            if (ModelState.IsValid)
            {
                string userId = User.Identity.GetUserId();
                var user = unitOfWork.Repository<ApplicationUser>().Get(u => u.Id == userId);

                var skill = new UserSkillWanted()
                {
                    Name = userSkill.Name,
                    Description = userSkill.Description,
                    UserId = userId,
                    SubrubricId = userSkill.SubrubricId
                };
                unitOfWork.Repository<UserSkillWanted>().Add(skill);
                unitOfWork.SaveChanges();

                var skillWanteds = unitOfWork.Repository<UserSkillWanted>().GetAll().Where(s => s.UserId == userId);
                return RedirectToAction("Index", "Profile");
            }
            return RedirectToAction("Index", "Profile");
        }

        // GET: UserSkills/Edit/5
        public ActionResult Edit(int id = 0)
        {
            UserSkillWanted skill = unitOfWork.Repository<UserSkillWanted>().Get(c => c.Id == id);
            if (skill == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubrubricId = new SelectList(unitOfWork.Repository<Subrubric>().GetAll() as IEnumerable<Subrubric>, "Id", "Name", skill.SubrubricId);
            return View(skill);

        }

        // POST: UserSkills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserSkillWanted userSkill)
        {
            if (userSkill.Name != string.Empty)
            {
                unitOfWork.Repository<UserSkillWanted>().Attach(userSkill);
                unitOfWork.SaveChanges();
                return RedirectToAction("Index", "Profile");
            }
            return RedirectToAction("Index", "Profile");

        }

        // GET: UserSkills/Delete/5
        public ActionResult Delete(int id = 0)
        {
            UserSkillWanted skill = unitOfWork.Repository<UserSkillWanted>().Get(c => c.Id == id);
            if (skill == null)
            {
                return HttpNotFound();
            }
            return View(skill);
        }

        // POST: UserSkills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserSkillWanted skill = unitOfWork.Repository<UserSkillWanted>().Get(c => c.Id == id);
            unitOfWork.Repository<UserSkillWanted>().Delete(skill);
            unitOfWork.SaveChanges();
            return RedirectToAction("Index", "Profile");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tech_No_Logic/Views/UserSkillWanteds/Create.cshtml
@model Tech_No_Logic.Models.UserSkillWanted

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserSkillWanted</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SubrubricId, "Subrubric", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubrubricId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubrubricId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tech_No_Logic/Views/UserSkillWanteds/Delete.cshtml
@model Tech_No_Logic.Models.UserSkillWanted

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserSkillWanted</h4>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
           Subrubric
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subrubric.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
        </div>
    }
</div>

Tech_No_Logic/Views/UserSkillWanteds/Edit.cshtml
@model Tech_No_Logic.Models.UserSkillWanted

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserSkillWanted</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.SubrubricId, "Subrubric", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubrubricId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubrubricId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tech_No_Logic/Views/UserSkillWanteds/Index.cshtml
@model IEnumerable<Tech_No_Logic.Models.UserSkillWanted>

@{
    ViewBag.Title = "Index";
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Subrubric)
        </th>
        <th>
            Skill
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Subrubric.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "UserSkillWanteds", new { id = item.Id },new { @class = "btn btn-info", @style = "padding-bottom:1px ;padding-top: 1px" }) 
                @Html.ActionLink("Delete", "Delete", "UserSkillWanteds", new { id = item.Id }, new { @class = "btn btn-danger", @style = "padding-bottom:1px ; padding-top: 1px" })
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Create New", "Create", "UserSkillWanteds", null, new { @class = "btn btn-success" })
</p>

Tech_No_Logic/Views/UserSkillWanteds/RequestIndex.cshtml
@model IEnumerable<Tech_No_Logic.Models.UserSkillWanted>

@{
    ViewBag.Title = "RequestIndex";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Subrubric)
        </th>
        <th>
            Skill
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Subrubric.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        </tr>
    }

</table>