Tech_No_Logic/Models/Request.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Tech_No_Logic.Models
{
    // в БД дописати тригер-перевірку, що відбуватиметься перед Insert.
    //  Тригер перевірятиме чи SkillTo.User.UserSkillWanted.Contains( SkillFrom.SubrubricId )
    // Тобто щоб наперед перевірити чи зацікавлений юзер, якому надсилають запит, у даному бартері.
    public class Request
    {
        [Key]
        public int Id { get; set; }

        public int SkillIdFrom { get; set; }

        [ForeignKey("SkillIdFrom")]
        public virtual UserSkill SkillFrom { get; set; }

        public int SkillIdTo { get; set; }

        [ForeignKey("SkillIdTo")]
        public virtual UserSkill SkillTo { get; set; }

        public string Message { get; set; }

        /// <summary>
        /// -1 means request was turned down
        /// 0 means request has not been considered yet
        /// 1 means request was submited
        /// </summary>
        [Range(-1, 1)]
        public int Status { get; set; }

        public DateTime DateOfSending { get; set; }

    }
}

Tech_No_Logic/Models/RequestViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Tech_No_Logic.Models
{
    public class RequestViewModel
    {
        // skill you are sugguesting
        [Display(Name = "Your skill")]
        public int SkillIdFrom { get; set; }

        [Display(Name = "Message")]
        public string Message { get; set; }
    }
}

Tech_No_Logic/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Tech_No_Logic.Models;
using Barter.DAL;

namespace Tech_No_Logic.Controllers
{
    [Authorize]
    [RequireHttps]
    public class ProfileController : Controller
    {
        private ApplicationUserManager _userManager;
        private UnitOfWork unitOfWork;
        public ProfileController()
        {
            unitOfWork = new UnitOfWork();
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var userController = new MeController(UserManager);
            var userViewModel = userController.Get();
            var model = new ProfileViewModel
            {
                FirstName = userViewModel.FirstName,
                LastName = userViewModel.LastName,
                HomeTown = userViewModel.Hometown,
                UserEmail = userViewModel.Email,
                Age = userViewModel.Age,
                Photo = userViewModel.Photo,
                PhoneNumber = UserManager.GetPhoneNumber(userId),
            };
            return View(model);
        }

        public ActionResult RequestIndex(string userId)
        {
            var user = UserManager.FindById(userId);
            var model = new ProfileViewModel
            {
                Id=user.Id,
                FirstName = user.FName,
                LastName = user.LName,
                HomeTown = user.Hometown,
                UserEmail = user.Email,
                Age = user.Age,
                Photo = user.Photo,
                PhoneNumber = UserManager.GetPhoneNumber(userId),
            };
            return View(model);
        }
        public ActionResult OtherUserSkills(string userId)
        {
            var skills = unitOfWork.Repository<UserSkill>().GetAll().Where(skill => skill.ApplicationUser.Id == userId) as IEnumerable<UserSkill>;
            return PartialView("~/Views/UserSkills/RequestIndex.cshtml", skills);
        }
        public ActionResult OtherUserSkillWanteds(string userId)
        {
            var skills = unitOfWork.Repository<UserSkillWanted>().GetAll().Where(skill => skill.ApplicationUser.Id == userId) as IEnumerable<UserSkillWanted>;
            return PartialView("~/Views/UserSkillWanteds/RequestIndex.cshtml", skills);
        }
        public ActionResult UserSkills()
        {
            string userId = User.Identity.GetUserId();
            var skills = unitOfWork.Repository<UserSkill>().GetAll().Where(skill => skill.ApplicationUser.Id == userId) as IEnumerable<UserSkill>;
            return PartialView("~/Views/UserSkills/Index.cshtml", skills);
        }
        public ActionResult UserSkillWanteds()
        {
            string userId = User.Identity.GetUserId();
            var skills = unitOfWork.Repository<UserSkillWanted>().GetAll().Where(skill => skill.ApplicationUser.Id == userId) as IEnumerable<UserSkillWanted>;
            return PartialView("~/Views/UserSkillWanteds/Index.cshtml", skills);
        }
    }
}

Tech_No_Logic/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Barter.DAL;
using Microsoft.AspNet.Identity;
using Tech_No_Logic.Models;

namespace Barter.Controllers
{
    [Authorize]
    public class RequestsController : Controller
    {
        private UnitOfWork unitOfWork = null;

        public RequestsController(UnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public RequestsController()
        {
            unitOfWork = new UnitOfWork();
        }

        public ActionResult Delete(int requestId = 0)
        {
            Request request = unitOfWork.Repository<Request>().Get(c => c.Id == requestId);
            unitOfWork.Repository<Request>().Delete(request);
            unitOfWork.SaveChanges();
            return RedirectToAction("Index", "Requests");
        }

        // GET: Requests
        public ActionResult Index()
        {
            return View(unitOfWork.Repository<Request>().GetAll() as IEnumerable<Request>);
        }
            
        // GET: OUTPUT Requests
        [ChildActionOnly]
        public ActionResult Output()
        {
            string userId = User.Identity.GetUserId();

            var skills = unitOfWork.Repository<Request>().GetAll().Where(request => request.SkillFrom.ApplicationUser.Id == userId) as IEnumerable<Request>;

            return PartialView("_Output", skills);
        }

        // GET: INPUT Requests
        [ChildActionOnly]
        public ActionResult Input()
        {
            string userId = User.Identity.GetUserId();

            var skills = unitOfWork.Repository<Request>().GetAll().Where(request => request.SkillTo.ApplicationUser.Id == userId) as IEnumerable<Request>;

            return PartialView("_Input", skills);
        }


        // GET: Requests/Create
        [HttpGet]
        public ActionResult Create(int UserSkillToId)
        {
            ViewBag.UserId = Guid.Parse(User.Identity.GetUserId());

            ViewBag.SkillToName = unitOfWork.Repository<UserSkill>().Get(s => s.Id == UserSkillToId).Name;

            ViewBag.SkillIdFrom = new SelectList(unitOfWork.Repository<UserSkill>().GetAll(sk => sk.UserId == User.Identity.GetUserId()) as IEnumerable<UserSkill>, "Id", "Name");
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RequestViewModel requestView, int UserSkillToId = 0)
        {
            if (ModelState.IsValid)
            {
                string userId = User.Identity.GetUserId();

                var request = new Request()
                {
                    SkillIdFrom = requestView.SkillIdFrom,
                    SkillIdTo = UserSkillToId,
                    Message = requestView.Message,
                    DateOfSending = DateTime.Now,
                    Status = 0
                };
                unitOfWork.Repository<Request>().Add(request);
                unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public ActionResult Accept(int requestId)
        {
            Request request = unitOfWork.Repository<Request>().Get(c => c.Id == requestId);
            if (request == null)
            {
                return HttpNotFound();
            }

            request.Status = 1;
            unitOfWork.Repository<Request>().Attach(request);
            unitOfWork.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Deny(int requestId)
        {
            Request request = unitOfWork.Repository<Request>().Get(c => c.Id == requestId);
            if (request == null)
            {
                return HttpNotFound();
            }

            request.Status = -1;
            unitOfWork.Repository<Request>().Attach(request);
            unitOfWork.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tech_No_Logic/Views/Requests/Create.cshtml
@model Tech_No_Logic.Models.Request

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Request</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.SkillIdTo, "To skill", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Label((string)ViewBag.SkillToName, htmlAttributes: new { @class = "control-label col-md-2" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SkillIdFrom, "From skill", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SkillIdFrom", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SkillIdFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tech_No_Logic/Views/Requests/Index.cshtml
@model IEnumerable<Tech_No_Logic.Models.Request>

@{
    ViewBag.Title = "Requests";
}

@*Тут потрібна таба для вхідних і вихідних запитів*@
<div style="margin-top:30px">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Input requests</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Output requests</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">@Html.Action("Input")</div>
        <div role="tabpanel" class="tab-pane" id="profile">@Html.Action("Output")</div>
    </div>

</div>

Tech_No_Logic/Views/Requests/_Input.cshtml
@model IEnumerable<Tech_No_Logic.Models.Request>

<h2>Input requests</h2>
<table class="table">
    <tr>
        <th></th>
        <th>
            User
        </th>
        <th>
            Skill
        </th>
        <th>
            Your skill
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfSending)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @if (item.SkillFrom.ApplicationUser.Photo != null)
                 {
                     @Html.Raw("<img id ='blah' style='object-fit:cover;width: 100px;height: 100px; ' class='img-thumbnail' src=\"data:image/jpeg;base64," + Convert.ToBase64String(item.SkillFrom.ApplicationUser.Photo) + "\" />")
                 }
                 else
                 {
                     <img id='blah' src="~/Content/Photos/default-profile-photo.png" class="img-thumbnail" style="object-fit: cover; width: 100px; height: 100px;"/>
                 }
        </td>
        <td>
            @Html.ActionLink(item.SkillFrom.ApplicationUser.FName+ " " + item.SkillFrom.ApplicationUser.LName, "RequestIndex", "Profile", new { userId = item.SkillFrom.ApplicationUser.Id }, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SkillFrom.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SkillTo.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfSending)
        </td>
        <td>
            @if (item.Status == -1)
            {
                @Html.ActionLink("Accept", "Accept", new {requestId = item.Id},new {@class="btn btn-success" })
            }
            else if (item.Status == 1)
            {
                @Html.ActionLink("Deny", "Deny", new {requestId = item.Id}, new { @class = "btn btn-danger" })
            }
            else
            {
                @Html.ActionLink("Accept", "Accept", new {requestId = item.Id}, new { @class = "btn btn-success",@style="margin: 5px" }) 
                @Html.ActionLink("Deny", "Deny", new {requestId = item.Id}, new { @class = "btn btn-danger" })
            }
        </td>
    </tr>
}

</table>

Tech_No_Logic/Views/Requests/_Output.cshtml
@model IEnumerable<Tech_No_Logic.Models.Request>

<h2>Output requests</h2>
<table class="table">
    <tr>
        <th></th>
        <th>
            User
        </th>
        <th>
            Your Skill
        </th>
        <th>
            Skill you want
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfSending)
        </th>
        <th>
            Status
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (item.SkillTo.ApplicationUser.Photo != null)
                {
                    @Html.Raw("<img id ='blah' style='object-fit:cover;width: 100px;height: 100px; ' class='img-thumbnail' src=\"data:image/jpeg;base64," + Convert.ToBase64String(item.SkillTo.ApplicationUser.Photo) + "\" />")
                }
                else
                {
                    <img id='blah' src="~/Content/Photos/default-profile-photo.png" class="img-thumbnail" style="object-fit: cover; width: 100px; height: 100px;" />
                }
            </td>
            <td>
                @Html.ActionLink(item.SkillTo.ApplicationUser.FName + " " + item.SkillTo.ApplicationUser.LName, "RequestIndex", "Profile", new { userId = item.SkillTo.ApplicationUser.Id }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SkillFrom.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SkillTo.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Message)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfSending)
            </td>
            <td>
                @if (item.Status == 1) { @Html.Label("Accepted",new {@class="text-success" })}
                else if (item.Status== -1) { @Html.Label("Rejected", new { @class = "text-danger" })}
                else { @Html.Label("Not considered", new { @class = "text-warning" })}
            </td>
            <td>
                @Html.ActionLink("Cancel", "Delete", "Requests", new {requestId = item.Id}, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>