Tech_No_Logic/Models/UserSkill.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Tech_No_Logic.Models
{
    /// <summary>
    /// Представляє "скіл" конкретного юзера
    /// </summary>
    public class UserSkill
    {
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Посилання на підрубрику 
        /// </summary>
        public int SubrubricId { get; set; }

        [ForeignKey("SubrubricId")]
        public virtual Subrubric Subrubric { get; set; }


        /// <summary>
        /// Посилання на юзера
        /// </summary>
        [Required]
        public string UserId { get; set; }

        [ForeignKey("UserId")]
        public virtual ApplicationUser ApplicationUser { get; set; }

        [Required]
        public string Name { get; set; }

        public string Description { get; set; }

        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public UserSkill()
        {
            Feedbacks = new List<Feedback>();
            Requests = new List<Request>();
        }
    }
}

Tech_No_Logic/Models/UserSkillViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Tech_No_Logic.Models
{
    public class UserSkillViewModel
    {
        [Required]
        [Display(Name = "Subrubrics")]
        public int SubrubricId { get; set; }

        [Required]
        [Display(Name = "Skill")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

Tech_No_Logic/Controllers/UserSkillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Barter.DAL;
using Tech_No_Logic.Models;
using Microsoft.AspNet.Identity;

namespace Tech_No_Logic.Controllers
{
    [Authorize]
    public class UserSkillsController : Controller
    {
        private UnitOfWork unitOfWork = null;

        public UserSkillsController()
        {
            unitOfWork = new UnitOfWork();
        }

        public UserSkillsController(UnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public ActionResult Search(string searchString)
        {
            if (String.IsNullOrEmpty(searchString)) return View();
            var skills = unitOfWork.Repository<UserSkill>().GetAll()
                .Where(s => s.Name.ToLower().Contains(searchString.ToLower()));
            return View(skills.ToList());
        }
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            var skills = unitOfWork.Repository<UserSkill>().GetAll().Where(skill => skill.ApplicationUser.Id == userId) as IEnumerable<UserSkill>;

            return PartialView("~/Views/UserSkills/Index.cshtml", skills);
        }

        // GET: UserSkills/Create
        public ActionResult Create()
        {
            ViewBag.UserId = Guid.Parse(User.Identity.GetUserId());
            ViewBag.SubrubricId = new SelectList(unitOfWork.Repository<Subrubric>().GetAll() as IEnumerable<Subrubric>, "Id", "Name");
            return View();
        }

        // POST: UserSkills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserSkillViewModel userSkill)
        {
            if (ModelState.IsValid)
            {
                string userId = User.Identity.GetUserId();
                var user = unitOfWork.Repository<ApplicationUser>().Get(u => u.Id == userId);
                var skill = new UserSkill()
                {
                    Name = userSkill.Name,
                    Description = userSkill.Description,
                    UserId = userId,
                    SubrubricId = userSkill.SubrubricId
                };
                unitOfWork.Repository<UserSkill>().Add(skill);
                unitOfWork.SaveChanges();

                var skills = unitOfWork.Repository<UserSkill>().GetAll().Where(s => s.UserId == userId);
                return RedirectToAction("Index", "Profile");
            }
            return RedirectToAction("Index", "Profile");
        }

        // GET: UserSkills/Edit/5
        public ActionResult Edit(int id = 0)
        {
            UserSkill skill = unitOfWork.Repository<UserSkill>().Get(c => c.Id == id);
            if (skill == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubrubricId = new SelectList(unitOfWork.Repository<Subrubric>().GetAll() as IEnumerable<Subrubric>, "Id", "Name", skill.SubrubricId);
            return View(skill);

        }

        // POST: UserSkills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserSkill userSkill)
        {
            if (userSkill.Name != string.Empty)
            {
                unitOfWork.Repository<UserSkill>().Attach(userSkill);
                unitOfWork.SaveChanges();
                return RedirectToAction("Index", "Profile");
            }
            return RedirectToAction("Index", "Profile");

        }

        

        // GET: UserSkills/Delete/5
        public ActionResult Delete(int id = 0)
        {
            UserSkill skill = unitOfWork.Repository<UserSkill>().Get(c => c.Id == id);
            if (skill == null)
            {
                return HttpNotFound();
            }
            return View(skill);
        }

        // POST: UserSkills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserSkill skill = unitOfWork.Repository<UserSkill>().Get(c => c.Id == id);
            unitOfWork.Repository<UserSkill>().Delete(skill);
            unitOfWork.SaveChanges();
            return RedirectToAction("Index", "Profile");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tech_No_Logic/Views/UserSkills/Create.cshtml
@model Tech_No_Logic.Models.UserSkill

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserSkill</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SubrubricId, "Subrubric", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubrubricId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubrubricId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tech_No_Logic/Views/UserSkills/Delete.cshtml
@model Tech_No_Logic.Models.UserSkill

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserSkill</h4>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            Subrubric
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subrubric.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> 
        </div>
    }
</div>

Tech_No_Logic/Views/UserSkills/Edit.cshtml
@model Tech_No_Logic.Models.UserSkill

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserSkill</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.SubrubricId, "Subrubric", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubrubricId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubrubricId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tech_No_Logic/Views/UserSkills/Index.cshtml
@model IEnumerable<Tech_No_Logic.Models.UserSkill>

@{
    ViewBag.Title = "Index";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Subrubric)
        </th>
        <th>
            Skill
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Subrubric.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "UserSkills", new { id = item.Id }, new { @class = "btn btn-info" ,@style="padding-bottom:1px ;padding-top: 1px" }) 
                @Html.ActionLink("Delete", "Delete", "UserSkills", new { id = item.Id }, new { @class = "btn btn-danger", @style = "padding-bottom:1px ; padding-top: 1px" })
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Create New", "Create", "UserSkills",null,new {@class="btn btn-success"})
</p>

Tech_No_Logic/Views/UserSkills/RequestIndex.cshtml
@model IEnumerable<Tech_No_Logic.Models.UserSkill>

@{
    ViewBag.Title = "RequestIndex";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Subrubric)
        </th>
        <th>
            Skill
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Subrubric.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Make request", "Create", "Requests", new { UserSkillToId = item.Id }, new { @class = "btn btn-success" })
            </td>
        </tr>
    }

</table>

Tech_No_Logic/Views/UserSkills/Search.cshtml
@using Tech_No_Logic.Models
@model IEnumerable<Tech_No_Logic.Models.UserSkill>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<form action="/UserSkills/Search" method="get">
    <p>
        Find by name: <input id="SearchString" name="SearchString" type="text" value="">
        <input type="submit" value="Search">
    </p>
</form>
<table class="table">
    <tr>
        <th></th>
        <th>
           User
        </th>
        <th>
           Hometown
        </th>
        <th>
           Subrubric
        </th>
        <th>
            Skill
        </th>
        <th>
            Description
        </th>
        <th></th>
        <th></th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
         {
             <tr>
                 <td>
                     @if (item.ApplicationUser.Photo != null)
                     {
                         @Html.Raw("<img id ='blah' style='object-fit:cover;width: 100px;height: 100px; ' class='img-thumbnail' src=\"data:image/jpeg;base64," + Convert.ToBase64String(item.ApplicationUser.Photo) + "\" />")
                     }
                     else
                     {
                         <img id='blah' src="~/Content/Photos/default-profile-photo.png" class="img-thumbnail" style="object-fit: cover; width: 100px; height: 100px;"/>
                     }
                 </td>
                 <td>
                     @Html.ActionLink(item.ApplicationUser.FName + " " + item.ApplicationUser.LName, "RequestIndex", "Profile",new { userId=item.ApplicationUser.Id},null)
                 </td>
                 <td>
                     @Html.DisplayFor(modelItem => item.ApplicationUser.Hometown)
                 </td>
                 <td>
                     @Html.DisplayFor(modelItem => item.Subrubric.Name)
                 </td>
                 <td>
                     @Html.DisplayFor(modelItem => item.Name)
                 </td>
                 <td>
                     @Html.DisplayFor(modelItem => item.Description)
                 </td>
                 <td>
                     @Html.ActionLink("Make request", "Create", "Requests", new {UserSkillToId = item.Id},new { @class = "btn btn-success" })
                 </td>
             </tr>
         }
    }

</table >
  